#!/usr/bin/env python3
"""Build lossless, self-contained foreground assets for /api/readme.svg."""

import base64
import importlib.util
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("hero", ROOT / "scripts/build-readme-hero.py")
hero = importlib.util.module_from_spec(spec)
spec.loader.exec_module(hero)


def image_uri(image: Image.Image, format: str = "PNG") -> str:
    output = io.BytesIO()
    image.save(output, format=format, optimize=True, lossless=True, quality=100, method=6)
    return f"data:image/{format.lower()};base64," + base64.b64encode(output.getvalue()).decode("ascii")


def main() -> None:
    title = Image.new("RGBA", (hero.WIDTH, hero.HEIGHT))
    hero.draw_title(title)
    frames = hero.load_logo_frames()
    atlas = Image.new("RGBA", (116 * hero.FRAME_COUNT, 99))
    for index in range(hero.FRAME_COUNT):
        # Keep source alpha; SVG applies the original breathing opacity separately.
        atlas.paste(hero.compose_logo(index, frames, apply_opacity=False), (116 * index, 0))
    atlas_uri = image_uri(atlas, "WEBP")
    output = ROOT / "functions/lib/readme-foreground.js"
    output.write_text(
        "// Generated by scripts/build-readme-foreground.py; do not edit by hand.\n"
        f"export const readmeTitle = '{image_uri(title)}';\n"
        f"export const readmeLogoAtlas = '{atlas_uri}';\n"
    )
    print(f"Built {output.relative_to(ROOT)} ({output.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
