#!/usr/bin/env python3
"""Build the project font subsets and self-contained SVG chart fonts."""

from __future__ import annotations

import argparse
import base64
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FONT_DIR = ROOT / "assets-src/fonts"
PUBLIC_FONT_DIR = ROOT / "public/assets/fonts"
SOURCE_EXTENSIONS = {".css", ".html", ".js", ".md", ".ts", ".tsx", ".txt"}
STATS_TEXT = "CCC Attendance 二维码生成趋势最近小时总计峰值最新历史累计生成总量自起统计数据库未配置绑定尚统计暂不可用UTC次年月日：·0123456789-., "


def collect_project_characters() -> str:
    files = [ROOT / "index.html", ROOT / "README.md"]
    for directory in (ROOT / "src", ROOT / "functions", ROOT / "public"):
        files.extend(path for path in directory.rglob("*") if path.suffix in SOURCE_EXTENSIONS)
    text = "".join(path.read_text(errors="ignore") for path in files)
    return "".join(sorted(set(text + STATS_TEXT)))


def subset_font(source: Path, output: Path, text_file: Path) -> None:
    subprocess.run(
        [
            "pyftsubset",
            str(source),
            f"--output-file={output}",
            "--flavor=woff2",
            f"--text-file={text_file}",
            "--layout-features=*",
            "--glyph-names",
            "--symbol-cmap",
            "--legacy-cmap",
            "--notdef-glyph",
            "--notdef-outline",
            "--recommended-glyphs",
        ],
        check=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stats-only", action="store_true", help="Only rebuild embedded SVG fonts")
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="ccc-font-build-") as temporary_directory:
        build_dir = Path(temporary_directory)
        project_text = build_dir / "project.txt"
        stats_text = build_dir / "stats.txt"
        project_text.write_text(collect_project_characters())
        stats_text.write_text(STATS_TEXT)

        embedded: dict[str, str] = {}
        for weight in ("W04", "W05"):
            source = SOURCE_FONT_DIR / f"TsangerJinKai02-{weight}.ttf"
            if not args.stats_only:
                subset_font(source, PUBLIC_FONT_DIR / f"TsangerJinKai02-{weight}-subset.woff2", project_text)
            stats_output = build_dir / f"TsangerJinKai02-{weight}-stats.woff2"
            subset_font(source, stats_output, stats_text)
            embedded[weight] = base64.b64encode(stats_output.read_bytes()).decode("ascii")

    module = ROOT / "functions/lib/qr-stats-fonts.js"
    module.write_text(
        "// Generated by scripts/build-font-subsets.py.\n"
        f"export const qrStatsFontRegular = '{embedded['W04']}';\n"
        f"export const qrStatsFontMedium = '{embedded['W05']}';\n"
    )

    print("Updated project font subsets and embedded SVG chart fonts")


if __name__ == "__main__":
    main()
